### PR TITLE
Реализовал аналайзер для аннотации @Before и соответствующие испключения

### PR DESCRIPTION
**Pull request by astronautr**
This change is [Reviewable](https://reviewable.io/reviews/declow0/junit-goty/1)

### CODE REVIEW

**Comment by astronautr** [comment]
[Реализовать анализатор Before](https://trello.com/c/mOOhU1ls/14-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80-before)

**Comment by Declow0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java, line 11 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KtegLO2_yaZMr-k5NuE:-Kteg6uwL2ckDfMfOCNw:b-31pr2f) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java#L11)):*
> beforeAnnotations > MAX_BEFORE_ANNOTATIONS
cl -> clazz

---

*[src/main/java/ru/specialcourse/java/exception/MultipleBeforeAnnotationException.java, line 4 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KteeVUbxKfYOO-npv3N:-KteeVUbxKfYOO-npv3O:b-e9jw3f) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/exception/MultipleBeforeAnnotationException.java#L4)):*
> ```Java
> 
> public class MultipleBeforeAnnotationException extends MultipleAnnotationException {
>     private static final String MESSAGE = "Multiple @Before annotation doesn't allowed here.";
> ```

Точка в конце не нужна

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/1)*

**Comment by Declow0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java, line 12 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KtegxwW-Vqp9ufE4XJT:-KtegxwW-Vqp9ufE4XJU:bt5ce44) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java#L12)):*
> MAX_BEFORE_ANNOTATIONS byte
beforeAnnotations -> byte

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/1)*

**Comment by Declow0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java, line 12 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KtegxwW-Vqp9ufE4XJT:-KtehEcPvRRegzQMmC2K:b-p1d2kf) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java#L12)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

> MAX_BEFORE_ANNOTATIONS byte
beforeAnnotations -> byte
</blockquote></details>

int -> byte

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/1)*

**Comment by astronautr** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java, line 11 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KtegLO2_yaZMr-k5NuE:-KtelQNhFVAK3wuwbrsF:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java#L11)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

> beforeAnnotations > MAX_BEFORE_ANNOTATIONS
cl -> clazz
</blockquote></details>

Done.

---

*[src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java, line 12 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KtegxwW-Vqp9ufE4XJT:-KtelQnRjrkTf0oWizOf:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/analyzer/BeforeAnnotationAnalyzer.java#L12)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

int -> byte
</blockquote></details>

Done.

---

*[src/main/java/ru/specialcourse/java/exception/MultipleBeforeAnnotationException.java, line 4 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/1#-KteeVUbxKfYOO-npv3N:-KtelTz6u3LqLNFHMd6p:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/df4cbab354c97fad19056383b9a83b332ecb7a31/src/main/java/ru/specialcourse/java/exception/MultipleBeforeAnnotationException.java#L4)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Точка в конце не нужна
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/1)*

**Comment by Declow0** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/1)*

**Pull request merged**
