### PR TITLE
Feature/16 assertion processing

### PR DESCRIPTION
**Pull request by astronautr**
This change is [Reviewable](https://reviewable.io/reviews/declow0/junit-goty/8)

### CODE REVIEW

**Comment by astronautr** [comment]
[Обработка Assertion](https://trello.com/c/WxZxERzC/16-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-assertion)

**Comment by Declow0** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 6 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktm6OWuUQSl_5-L2K8Y:-Ktm6OWuUQSl_5-L2K8Z:bpxdi5) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L6)):*
> ```Java
> 
> public class Assert {
>     protected Assert() {
> ```

Почему не private?

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 146 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmIFVWOa9fTn820NHR:-KtmIFVWOa9fTn820NHS:bp0ksnj) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L146)):*
> ```Java
>     public static void assertEquals(String message, String  expected, String actual) {
>         if (!expected.equals(actual)) {
>             failEquals(message, expected, actual);
> ```

failNotEquals

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 155 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmEy7ogu1CjKyzAb6f:-KtmEy7ogu1CjKyzAb6g:bv4m51r) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L155)):*
> ```Java
> 
>     public static void assertNotEquals(String message, String unexpected, String actual) {
>         assertNotEquals(message, String.valueOf(unexpected), String.valueOf(actual));
> ```

Рекурсия? Может избавиться от отдельной реализации для String поскольку он наследник Object?

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 192 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmE9z4wbcKGK9zkH1R:-KtmE9z4wbcKGK9zkH1S:b-1n6lvj) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L192)):*
> ```Java
>     }
> 
>     private static void failEquals(String message, Object expected, Object actual) {
> ```

Это что означает? Падать, когда равны или падать assertEquals (скорее всего первое)? Просто один раз он используется в assertNotEquals для Object, другой в assertEquals для String.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 196 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmFFgyw50WikNXN1UL:-KtmFFgyw50WikNXN1UM:bbvz29k) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L196)):*
> ```Java
>     }
> 
>     private static void failNotEquals(String message, Object expected, Object actual) {
> ```

Тот же вопрос, что и для failEquals. Как и для чего?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 207 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmKQlNsBmFxpn74pdI:-KtmKQlNsBmFxpn74pdJ:b-fhlz4j) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L207)):*
> ```Java
>         return formatted + "expected:<" + expected + "> but was:<" + actual + ">";
>     }
>     private static String formatUnExpected(String message, Object expected, Object actual) {
> ```

Где отступ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 120 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktnr-UNlsVjK0lkTxXV:-Ktnr-UOnmT-m5QdqAd2:b-1t3a2m) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L120)):*
> ```Java
>     }
> 
>     public static void assertNotEquals(String message, double unexpected, double actual) {
> ```

Вообще мне кажется для чисел с плавающей точкой надо использовать compare и сравнивать с 0.
Вот пример из интернета:

double dd = 3.5;          
float ff = 3.5f;
System.out.println(dd==ff);   
o/p: true

double dd = 3.2;
float ff = 3.2f;
System.out.println(dd==ff);
o/p: false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by astronautr** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 6 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktm6OWuUQSl_5-L2K8Y:-KtoEPtKQNijk4d1jvN8:bbnmnzs) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L6)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Почему не private?
</blockquote></details>

Потому что если мы захотим сделать наследника Assert, у которого будет конструктор, то в случае с приватным конструктором нам придётся добавлять конструктор в классе Assert который будет доступен для чайлда (не можем вызвать приватный конструктор суперкласса), иначе не сможем скомпилировать класс потомка.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 120 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktnr-UNlsVjK0lkTxXV:-KtoFt4ltx1YiNXCXkmK:b-e6eyzr) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L120)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Вообще мне кажется для чисел с плавающей точкой надо использовать compare и сравнивать с 0.
Вот пример из интернета:

double dd = 3.5;          
float ff = 3.5f;
System.out.println(dd==ff);   
o/p: true

double dd = 3.2;
float ff = 3.2f;
System.out.println(dd==ff);
o/p: false
</blockquote></details>

Заметь я написал сравнения только для примитивных типов и с возможностью сравнивать только с объектами ТОГО ЖЕ ТИПА. Поэтому, как мне кажется твой пример неактуален. Либо приведи ещё аргументы.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 146 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmIFVWOa9fTn820NHR:-KtoGI11FfEkfiBkOSuE:b-kx23hn) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L146)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

failNotEquals
</blockquote></details>

Тут используется `failEquals` т.к. его вызов подразумевает что была провалена проверка на равенство. Здесь ничего не нужно менять. Это на строке 167 нужно было заменить `failNotEquals` на `failEquals` как раз таки.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 155 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmEy7ogu1CjKyzAb6f:-KtoIZAXWocIrlOESPZ8:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L155)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Рекурсия? Может избавиться от отдельной реализации для String поскольку он наследник Object?
</blockquote></details>

Done.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 192 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmE9z4wbcKGK9zkH1R:-KtoIaWdn239rWh8c9LW:brblblv) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L192)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Это что означает? Падать, когда равны или падать assertEquals (скорее всего первое)? Просто один раз он используется в assertNotEquals для Object, другой в assertEquals для String.
</blockquote></details>

Объяснил выше - падаем когда провалена проверка на равенство. То что я использовал неправильную вещь - моя ошибка, поправил.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 196 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmFFgyw50WikNXN1UL:-KtoIpldOmN_bBIN8V93:bjc8vpi) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L196)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Тот же вопрос, что и для failEquals. Как и для чего?
</blockquote></details>

Падаем когда провалена проверка на неравенство.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 207 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtmKQlNsBmFxpn74pdI:-KtoE9vIbQ0aQLLntX_A:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L207)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Где отступ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 120 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktnr-UNlsVjK0lkTxXV:-KtqSNDcKliLTzpdKdo4:bnurfwh) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L120)):*
<details><summary><i>Previously, DmitryGerasimenko (Dmitry Gerasimenko) wrote…</i></summary><blockquote>

Заметь я написал сравнения только для примитивных типов и с возможностью сравнивать только с объектами ТОГО ЖЕ ТИПА. Поэтому, как мне кажется твой пример неактуален. Либо приведи ещё аргументы.
</blockquote></details>

Я понял, создали так 2 числа, оба кастанули в double. Беда. Хотя скорее всего так и должно быть... Ответь, расскажи свои мысли по поводу, может заапрувлю...

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 187 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqWs7uTE2vUy455GET:-KtqWs7uTE2vUy455GEU:baf5bav) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L187)):*
> ```Java
>             formatted = message + " ";
>         }
>         return formatted + "expected:<" + expected + "> but was:<" + actual + ">";
> ```

Было бы неплохо выводить еще и класс. Пример:
Assert.assertEquals("3.0", 3.f);

Вывод от JUNIT:
expected: java.lang.String<3.0> but was: java.lang.Float<3.0>


Наш вывод:
expected:<3.0> but was:<3.0>

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 190 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqZ2lNsX4pkR8JkAnd:-KtqZ2lNsX4pkR8JkAne:b-u8cd8c) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L190)):*
> expected
Переименовать в unExpected?

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 195 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqXxdNYmznqq36Itvc:-KtqXxdNYmznqq36Itvd:b-ortfnv) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L195)):*
> ```Java
>             formatted = message + " ";
>         }
>         return formatted + "unexpected:<" + expected + "> but was:<" + actual + ">";
> ```

Тоже самое, что и с excepted.
Может переформулировать?
actual:<?> but should be different

А то получается одно и тоже значение 2 раза выводим...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 190 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqZ2lNsX4pkR8JkAnd:-Ktq_mBx1ulaKyz_NSMM:bv4s7sl) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L190)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

> expected
Переименовать в unExpected?
</blockquote></details>

unexpected все маленькими... Это ж одно слово

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 190 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqZ2lNsX4pkR8JkAnd:-KtrC8BeIwP481XUqRqk:b-hkdr88) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L190)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

unexpected все маленькими... Это ж одно слово
</blockquote></details>

unexpected вообще не нужен. Нужен только actual

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by astronautr** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 120 at r1](https://reviewable.io:443/reviews/declow0/junit-goty/8#-Ktnr-UNlsVjK0lkTxXV:-Ktt96v1AKj_ZOsHm-Gv:b5qf5fm) ([raw file](https://github.com/declow0/junit-goty/blob/1a3a5bdce78ada55ce964c653c0db1893e12947b/src/main/java/ru/specialcourse/java/assertion/Assert.java#L120)):*
> Я понял, создали так 2 числа, оба кастанули в double. Беда. Хотя скорее всего так и должно быть... Ответь, расскажи свои мысли по поводу, может заапрувлю...
Ну по сути ты сам всё сказал: "Беда. Хотя скорее всего так и должно быть". Логично что при сравнении примитивов разных типов данных мы ничего не можем гарантировать в данной реализации. Мне и не хочется заморачиваться чтобы можно было что-то гарантировать, и вот почему: я не представляю use-case'а где тебе для проверки верной работы функции нужно было бы использовать объект отличеного типа от того что возвращает проверяемся функция. Про дельту сказано правильно - её реализация нужна: например, как без неё удобно проверить работу `Math.sqrt(arg)`?

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 187 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqWs7uTE2vUy455GET:-KttDGuu0EFFEtGOb2qk:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L187)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Было бы неплохо выводить еще и класс. Пример:
Assert.assertEquals("3.0", 3.f);

Вывод от JUNIT:
expected: java.lang.String<3.0> but was: java.lang.Float<3.0>


Наш вывод:
expected:<3.0> but was:<3.0>
</blockquote></details>

Done.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 190 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqZ2lNsX4pkR8JkAnd:-KttCG8fMtSu-irugyDu:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L190)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

unexpected вообще не нужен. Нужен только actual
</blockquote></details>

Done.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 195 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqXxdNYmznqq36Itvc:-KttEeskyz8K1RSAHsmO:b-896fix) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L195)):*
<details><summary><i>Previously, Declow0 (Roman Babkov) wrote…</i></summary><blockquote>

Тоже самое, что и с excepted.
Может переформулировать?
actual:<?> but should be different

А то получается одно и тоже значение 2 раза выводим...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/ru/specialcourse/java/assertion/Assert.java, line 195 at r2](https://reviewable.io:443/reviews/declow0/junit-goty/8#-KtqXxdNYmznqq36Itvc:-KtthX5mS__jzNgI7pkb:b-vamgd2) ([raw file](https://github.com/declow0/junit-goty/blob/9a41ccbab58bd050bb333e341bf3c36b93283648/src/main/java/ru/specialcourse/java/assertion/Assert.java#L195)):*
<details><summary><i>Previously, DmitryGerasimenko (Dmitry Gerasimenko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Можно сначала message, потом текст values... but actual?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Comment by Declow0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/declow0/junit-goty/8)*

**Pull request merged**
